[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
send_message = '0xf97a9790c591bd4127e363fe1cb49cf391cfff9150f858376cb9adcae2fb9b16'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]